### ISSUE TITLE
Use once to register to signals

### ISSUE THREAD

**Issue by mcollina** [hemerajs/fastify-graceful-shutdown#3]
a double Ctrl-C should kill the process.

**Comment by StarpTech** [comment]
Nice catch will fix it asap

**Comment by bttger** [comment]
@mcollina @StarpTech I've just spent two hours debugging why the `onClose` hooks were never called. When I pressed Ctrl-C, my fastify instance always received two SIGINT events and thus the server immediately shut down without running the `onClose` hook anymore.

After so many tries, I finally found out, that it's because I had an npm script to start the server. Starting the script directly with the node executable works.

Btw, it's easy to reproduce (Start it through an npm script):

```js
import Fastify from "fastify";

const server = Fastify({ logger: true });

const signals = ["SIGINT", "SIGTERM"];
signals.forEach((signal) => {
  process.on(signal, () => {
    server.log.info({ signal: signal }, "received termination signal");
    server.close();
  });
});

const start = async () => {
  try {
    await server.listen({ port: 3000, host: "0.0.0.0" });
  } catch (err) {
    server.log.error(err);
    process.exit(1);
  }
};

start();
```
... pressing Ctrl-C prints the signal twice. And only once when started with node.

**Comment by ardasevinc** [comment]
> @mcollina @StarpTech I've just spent two hours debugging why the `onClose` hooks were never called. When I pressed Ctrl-C, my fastify instance always received two SIGINT events and thus the server immediately shut down without running the `onClose` hook anymore.
> 
> After so many tries, I finally found out, that it's because I had an npm script to start the server. Starting the script directly with the node executable works.
> 
> Btw, it's easy to reproduce (Start it through an npm script):
> 
> ```js
> import Fastify from "fastify";
> 
> const server = Fastify({ logger: true });
> 
> const signals = ["SIGINT", "SIGTERM"];
> signals.forEach((signal) => {
>   process.on(signal, () => {
>     server.log.info({ signal: signal }, "received termination signal");
>     server.close();
>   });
> });
> 
> const start = async () => {
>   try {
>     await server.listen({ port: 3000, host: "0.0.0.0" });
>   } catch (err) {
>     server.log.error(err);
>     process.exit(1);
>   }
> };
> 
> start();
> ```
> 
> ... pressing Ctrl-C prints the signal twice. And only once when started with node.

I spent a week pondering why this happened. In my case, graceful shutdown gets triggered when the server sits open a period of time. I'm also starting the server from an npm script. Everything works if I start the server directly. 

What's the solution if we want to keep using npm scripts?
